### ISSUE TITLE
Unit tests fails in Safari 5.1.7

### ISSUE THREAD

**Issue by v3nom** [axemclion/IndexedDBShim#30]
Unit tests: 22, 25 and 26 fails in Safari 5.1.7 on Windows 8.

**Comment by axemclion** [comment]
Not able to reproduce the error. Occured the first time, but went away on refreshing the page. Looks like this is due to the way, the index tests were written. Are you able to reproduce this consistently ? 

Here is the test I ran - https://saucelabs.com/tests/93af02b4eaf042ad8b34ddd1223f389b

Closing the issue for now, please do reopen if you keep seeing this issue.
